config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :restaurants , only: [:index, :destroy, :edit, :update]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }, numericality: true
  belongs_to :restaurant, required: true
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [ :new, :create ]

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<div>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/admin/restaurants/edit.html.erb
<h2>Edit a restaurant</h2>

<%= render 'form' %>

app/views/admin/restaurants/index.html.erb
<h2>All restaurants</h2>
<p><%= link_to "Add a new restaurant", new_restaurant_path %></p>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <h4><%= link_to restaurant.name, restaurant_path(restaurant) %> - <%= restaurant.category %></h4>
      <p><%= restaurant.address %></p>
      <p><%= link_to "Edit", edit_admin_restaurant_path(restaurant) %> | <%= link_to "Delete", admin_restaurant_path(restaurant), method: :delete %></p>
    </li>
  <% end %>
</ul>

app/views/admin/restaurants/new.html.erb
<h2>Add a new restaurant</h2>

<%= render 'form' %>

app/views/admin/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

<div>
  <p>Category: <%= @restaurant.category %></p>
  <p>Address: <%= @restaurant.address %></p>
  <p>Phone: <%= @restaurant.phone_number %></p>
</div>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>

<h4>Reviews</h4>
<ul>
  <% @restaurant.reviews.each do |review| %>
  <li><%= review.content%> - <%= "*" * review.rating %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lacuillere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>
  <%= render "shared/navbar" %>
  <div class="content">
    <%= yield %>
  </div>
    <%= render "shared/footer" %>
</body>
</html>

app/views/restaurants/_form.html.erb
<div>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<h2>All restaurants</h2>
<p><%= link_to "Add a new restaurant", new_restaurant_path %></p>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <h4><%= link_to restaurant.name, restaurant_path(restaurant) %> - <%= restaurant.category %></h4>
      <p><%= restaurant.address %></p>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h2>Add a new restaurant</h2>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

<div>
  <p>Category: <%= @restaurant.category %></p>
  <p>Address: <%= @restaurant.address %></p>
  <p>Phone: <%= @restaurant.phone_number %></p>
</div>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>

<h4>Reviews</h4>
<ul>
  <% @restaurant.reviews.each do |review| %>
  <li><%= review.content%> - <%= "*" * review.rating %></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<div>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Add a review" %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>This is my footer</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to admin_restaurants_path do %>
              <i class="fa fa-user"></i> <%= t ".profile", default: "Admin" %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add new restaurant"), new_restaurant_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>